# Generated by Django 6.0.5 on 2026-05-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="item_details",
            field=models.TextField(default="", verbose_name="تفاصيل السلعة ومواصفاتها"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="item_title",
            field=models.CharField(
                default="", max_length=100, verbose_name="عنوان السلعة المعروضة"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(
                default=0, verbose_name="الكمية المتوفرة بالمخزن"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="تكلفة الوحدة",
            ),
            preserve_default=False,
        ),
    ]
