# Generated by Django 6.0.5 on 2026-05-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_description_remove_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, verbose_name="الكمية المطلوبة"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="اسم المشتري"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="رقم الهاتف"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الطلب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="shop.product",
                        verbose_name="المنتج المطلوب",
                    ),
                ),
            ],
        ),
    ]
