# Generated by Django 5.2.14 on 2026-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('order_number', models.IntegerField(verbose_name='رقم الطلب')),
                ('address', models.CharField(max_length=200, verbose_name='عنوان التوصيل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Delivered', 'تم التوصيل'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='حالة الطلب')),
            ],
        ),
    ]
