# Generated by Django 6.0.5 on 2026-05-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="address",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="order_number",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="status",
        ),
        migrations.AddField(
            model_name="delivery",
            name="contact_number",
            field=models.CharField(
                default="", max_length=20, verbose_name="رقم التواصل الهاتفي"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_destination",
            field=models.CharField(
                default="", max_length=200, verbose_name="وجهة التوصيل والمنطقة"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="recipient_full_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="الاسم الكامل للمستلم"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="shipment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "قيد التحقق والاستلام"),
                    ("Delivered", "تم التوصيل للعميل"),
                    ("Cancelled", "ملغي من قبل الإدارة"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="حالة الشحنة",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="tracking_number",
            field=models.IntegerField(default=0, verbose_name="رقم التتبع للطلب"),
            preserve_default=False,
        ),
    ]
